site_name: PYPSSE

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
          python:
            paths: [src]
  - glightbox

nav:
  - :Index.md
  - installation.md
  - how-to-guides.md
  - Tutorials : tutorials.md
  - Server : server_example.md
  - References :
      Models: code/models.md
      Code reference: code/reference.md

  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

hooks:
  - docs/code/endantic.py