[Simulation]
"Simulation time (sec)" = 25
"Step resolution (sec)" = 1 #0.00416667
"Start time" = "01/01/2020 00:00:00"
"Simulation mode" = "Steady-state"
"Use profile manager" = true
"PSSE_path" = "C:/Program Files (x86)/PTI/PSSE34/PSSPY37"
"Project Path" = ""
"Case study" = "" 
"Raw file" =  ""
"Snp file" = ""
"Dyr file" = ""
"GIC file" = ""
"Rwm file" = ""

"User models" = [""]
"Setup files" = []

[HELICS]
"Cosimulation mode" = false
"Federate name" = "psse"
"Time delta" = 0.004166667
"Core type" = "zmq"
"Uninterruptible" = true
"Helics logging level" = 5
"Create subscriptions" = true
"Iterative Mode" = false
"Error tolerance" = 0.00001
"Max co-iterations" = 15

[Export_settings]
"Outx file" = "Results.outx"
"Out file" = "Results.out"
"Excel file" = "Results.xls"
"Log file" = "Results.log"
"Coordinate file" = "Coordinates.csv"
"NetworkX graph file" = "Graph.gpickle"

[Logging]
"Disable PSSE logging" = true
"Logging Level" = "DEBUG"
"Log to external file" = false
"Display on screen" = true
"Clear old log file" = true
"Pre-configured logging" = false


[Plotting]
"Enable dynamic plots" = false
"columns" = 2

[GIC_export_settings]
"include substation connections" = false
"include transfomer connections" = false
"include branch connections" = true

[bus_subsystems]
"from_file" = false
"bus_file" = ""
"bus_subsystem_list" = []
"publish_subsystems" = [0]

[Loads]
"Convert" = false
[Loads.active_load]
"% constant current" = 50.0
"% constant admittance" = 50.0
[Loads.reactive_load]
"% constant current" = 50.0
"% constant admittance" = 50.0

[Generators]
"Missing machine model" = 1 # 0: treat as a fatal error 1: replace with net machine power

# [contingencies.bus_fault.bf_1]
# "time" = 1.0
# "bus_id" = 25048#25824, 25059
# "duration" = 0.1
# "bus_trip" = true
# "trip_delay" = 5.0
# "fault_impedance" = [0.0001, 0.00000001]

# [contingencies.machine_trip.mt_1]
# "time" = 100.0
# "bus_id" = 21528
# "machine_id" = "1"

# [contingencies.bus_trip.bt_1]
# "time" = 100.0
# "bus_id" = 50435

# [contingencies.line_trip.lt_1]
# "time" = 100.0
# "bus_ids" = [21528, 21542]

# [contingencies.line_fault.lf_1]
# "time" = 100.0
# "bus_ids" = [21528, 21542]
# "duration" = 0.01667
# "fault_impedance" = [0.3, 0.00000001]

