[simulation]
simulation_time = 30.0
simulation_step_resolution = 1.0
psse_solver_timestep = 0.004166667
start_time = "2020-01-01 00:00:00.0"
simulation_mode = "Steady-state"
use_profile_manager = false
psse_path = "C:/Program Files/PTI/PSSE35/35.4/PSSPY39"
project_path = "."
case_study = ""
raw_file = ""
dyr_file = ""
rwm_file = ""
gic_file = ""
snp_file = ""
subscriptions_file = ""

[export]
outx_file = ""
out_file = ""
excel_file = ""
log_file = ""
coordinate_file = ""
networkx_graph_file = ""

[helics]
cosimulation_mode = false
federate_name = "psse"
time_delta = 0.00333333333
core_type = "zmq"
uninterruptible = true
helics_logging_level = 5
create_subscriptions = true
iterative_mode = false
error_tolerance = 1e-5
max_coiterations = 15
subscription_file = ""
broker_ip = "127.0.0.1"
broker_port = 23404
disable_generation_on_coupled_buses = true
[[helics.publications]]
bus_subsystems = [ 0,]
asset_type = "Buses"
asset_properties = [ "FREQ", "PU",]

[log]
disable_psse_logging = true
logging_level = 10
log_to_external_file = true
display_on_screen = true
clear_old_log_file = true
pre_configured_logging = false

[plots]
enable_dynamic_plots = false
columns = 2

[bus_subsystems]
from_file = false
bus_file = ""
bus_subsystem_list = [ [ 153, 154, 203, 205, 3005, 3007, 3008,],]
publish_subsystems = [ 0,]

[loads]
convert = false
[loads.active_load]
constant_current_percentage = 0.0
constant_admittance_percentage = 0.0
[loads.reactive_load]
constant_current_percentage = 0.0
constant_admittance_percentage = 0.0

[generators]
missing_machine_model = 1

[[contingencies]]
time = 87000.0
bus_id = 102
duration = 0.1
bus_trip = false
trip_delay = 0.05
fault_impedance = [ 0.001, 0.001,]
