export_results_using_channels = false
defined_subsystems_only = true
file_format = "h5"

buses = ["PU", "ANGLED", "FREQ"]
areas = ["GEN", "AREANAME", "AREANUMBER"]
zones = ["LOAD", "LOADID"]
stations = ["SUBNAME", "SUBNUMBER"]
loads = ["MVA", "FmA" ,"FmB", "FmC", "FmD", "Fel", "PFel"]
Branches = ["MVA", "AMPS", "PUCUR"]
induction_generators = ["MVA"]
machines = ["MVA", "PERCENT"]
channels = ["ANGLE = false machine relative rotor angle (degrees)." , "flow (P)." ]

[[channel_setup]]
asset_type = "buses"
use = "list" # "regex", "list", "all"
regex = ""
asset_list = [153, 154]
asset_properties = ["voltage_and_angle", "frequency"]

[[channel_setup]]
asset_type = "buses"
use = "list" # "regex", "list", "all"
regex = ""
asset_list = [206, 3018]
asset_properties = ["voltage_and_angle"]

[[channel_setup]]
asset_type = "loads"
use = "list" # "regex", "list", "all"
regex = ""
asset_list = [["1", "153"], ["2", "154"], ["1", "203"], ["1", "205"], ["1", "3005"], ["1", "3007"], ["1", "3008"]]

[[channel_setup]]
asset_type = "machines"
use = "list" # "regex", "list", "all"
regex = ""
asset_list = [["1", "101"], ["1", "102"], ["1", "206"], ["1", "211"], ["1", "3011"], ["1", "3018"]]
asset_properties = ["PELEC", "QELEC", "SPEED"]